### ISSUE TITLE
Assertion `!memcmp(expected_signature, sig, len)' failed.

### ISSUE THREAD

**Issue by biemster** [Smoothstep/apple-gen#2]
I might have compiled this incorrectly, since the CMakeList for the test did throw an error on the `-stack` linker parameter. I'm on GCC 13.2.1. Building the lib went fine, but then I build the test like this:
```bash
g++ apple-gen.cpp -o apple-gen ../build/lib/libapple_crypto.a -I../include/
```
I'll try to fix this `-stack` parameter because I expect that to be the problem, but since I don't have any experience with that any help would be appreciated as well.

**Comment by biemster** [comment]
Same issue on clang 16.0.6. OS is manjaro

**Comment by Smoothstep** [comment]
The stack flag varies accross linkers and I didn't include support for all of them. This flag isn't important, as long as the default stack value is about ~64 KB.
You may ignore the test project, as it was only added for demonstration purposes. The resulting bytes of the validation blob aren't deterministic accross systems unfortunately, but that has no real impact. I didn't actually check what caused this.

**Comment by biemster** [comment]
Ah great! I'm going to try to generate some known values then as a test. I'll close this if I succeed.

**Comment by biemster** [comment]
Yup works fine even though the signatures seem to be platform dependent, closing.
